# Setup
title:        Unathema Studios
tagline:      Building apps and fighting consoles.
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       UnathemaStudios
  url:        mailto:UnathemaStudios@gmail.com

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown